#!/usr/bin/env bash
#
# Main installer. Invoked by ../install.sh after the payload is in /opt.
#
# Idempotent by construction: re-running on a configured machine reuses the
# existing ports, keeps the database and its data, and reapplies configuration.
#
# The agent finishes INSTALLED BUT PAUSED. Nothing is collected and no disk is
# consumed until retention and a service selection are set from the app or CLI.

set -euo pipefail

PREFIX=/opt/ai-terminal-logs
. "$PREFIX/lib/common.sh"

PG_PORT_WANTED="$PG_PORT_DEFAULT"
while [ $# -gt 0 ]; do
  case "$1" in
    --port) PG_PORT_WANTED="${2:?--port needs a value}"; shift 2 ;;
    *) shift ;;
  esac
done
export PG_PORT_WANTED

require_root

VERSION=$(cat "$PREFIX/VERSION" 2>/dev/null || echo "0.0.0")
log "ai-terminal-logs $VERSION"

# ── 1. reclaim disk before adding a log store to it ──────────────────────────
. "$PREFIX/lib/preflight.sh"
preflight

# ── 2. detect the environment; never assume paths ────────────────────────────
. "$PREFIX/lib/detect.sh"
detect

install -d -m 755 "$STATE" "$STATE/vector"
install -d -m 700 "$ETC"

PM2_LOG_DIRS_CSV=""
for d in ${PM2_LOG_DIRS[@]+"${PM2_LOG_DIRS[@]}"}; do
  PM2_LOG_DIRS_CSV="$PM2_LOG_DIRS_CSV\"$d/*.log\", "
done
PM2_LOG_DIRS_CSV="${PM2_LOG_DIRS_CSV%, }"

cat > "$ENV_FILE" <<EOF
# GENERATED by ai-terminal-logs installer
PG_CONTAINER=$PG_CONTAINER
PG_VOLUME=$PG_VOLUME
PG_USER=$PG_USER
PG_DB=$PG_DB
PG_PORT=$PG_PORT
RECEIVER_PORT=$RECEIVER_PORT
HOST_NAME=$HOST_NAME
TZ_NAME=$TZ_NAME
HAS_JOURNAL=$HAS_JOURNAL
NGINX_LOG_DIR=$NGINX_LOG_DIR
PM2_LOG_DIRS_CSV=$(printf '%q' "$PM2_LOG_DIRS_CSV")
AGENT_VERSION=$VERSION
EOF
chmod 600 "$ENV_FILE"

# Paused, no retention, no services. Disk stays untouched until configured.
if [ ! -f "$CONF" ]; then
  cat > "$CONF" <<'EOF'
{
  "paused": true,
  "days": null,
  "sources": {
    "pm2": true,
    "docker": true,
    "systemd": true,
    "nginx": "off",
    "redis": false
  },
  "logServices": [],
  "metricsAll": true
}
EOF
  chmod 600 "$CONF"
  log "wrote default config (paused, no retention set)"
else
  log "existing config preserved"
fi

[ -f "$CHANNELS" ] || { echo '{}' > "$CHANNELS"; chmod 600 "$CHANNELS"; }

# ── 3. logs database ─────────────────────────────────────────────────────────
. "$PREFIX/lib/database.sh"
install_db
apply_schema

# ── 4. vector ────────────────────────────────────────────────────────────────
install_vector() {
  if command -v vector >/dev/null 2>&1; then
    log "vector present ($(vector --version 2>/dev/null | head -1))"
    return 0
  fi
  log "installing vector"
  curl -fsSL https://sh.vector.dev | bash -s -- -y --prefix /usr/local >/dev/null 2>&1 \
    || die "vector install failed — see https://vector.dev/docs/setup/installation/"
  export PATH="$PATH:/usr/local/bin"
  command -v vector >/dev/null 2>&1 || die "vector installed but not on PATH"
}
install_vector

# ── 5. CLI ───────────────────────────────────────────────────────────────────
install -m 755 "$PREFIX/bin/logagent" /usr/local/bin/logagent

# ── 6. systemd units ─────────────────────────────────────────────────────────
log "installing systemd units"
install -m 644 "$PREFIX/systemd/"*.service /etc/systemd/system/
install -m 644 "$PREFIX/systemd/"*.timer   /etc/systemd/system/
systemctl daemon-reload

systemctl enable --now ai-terminal-receiver.service >/dev/null 2>&1 \
  || warn "receiver failed to start — check: journalctl -u ai-terminal-receiver"
systemctl enable --now ai-terminal-partitions.timer >/dev/null 2>&1 || true
systemctl enable --now ai-terminal-watchdog.timer   >/dev/null 2>&1 || true
systemctl enable --now ai-terminal-metrics.timer    >/dev/null 2>&1 || true
systemctl enable --now ai-terminal-rollup.timer     >/dev/null 2>&1 || true
systemctl enable --now ai-terminal-alerts.timer     >/dev/null 2>&1 || true
systemctl enable --now ai-terminal-probes.timer     >/dev/null 2>&1 || true

# ── 7. first partitions + vector config ──────────────────────────────────────
bash "$PREFIX/lib/partitions.sh" >/dev/null 2>&1 || warn "initial partition creation failed"
bash "$PREFIX/lib/vector-config.sh" >/dev/null 2>&1 || warn "initial vector config generation failed"
# Seed the rollup so the dashboard is not blank the first time it is opened.
bash "$PREFIX/lib/rollup.sh" >/dev/null 2>&1 || true

# Paused until configured — vector must not start yet.
systemctl stop vector >/dev/null 2>&1 || true

# ── 8. report ────────────────────────────────────────────────────────────────
cat <<EOF

$(log "install complete")

  agent       $VERSION  —  PAUSED, collecting nothing
  host        $HOST_NAME   (timezone $TZ_NAME)
  database    127.0.0.1:$PG_PORT/$PG_DB   user=$PG_USER
  password    $ETC/pgpass
  free disk   $(gb "$(free_bytes)") GB

  Discovered: $(logagent status 2>/dev/null | python3 -c 'import json,sys;d=json.load(sys.stdin)["discovered"];print(f"{len(d)} services")' 2>/dev/null || echo "run: logagent status")

  Next — choose retention and services, from the app or here:

      logagent set --json '{"days":7,"logServices":["my-api","postgres17"]}'

  Then verify:

      logagent status

EOF
