#!/usr/bin/env bash
# Generate /etc/vector/vector.toml from the current selection in logagent.conf.
#
# Standalone and idempotent, so `logagent set` can rebuild the config and restart
# Vector without reinstalling anything.
#
# Sources are declared per source TYPE, never per service. A new PM2 app or
# container is picked up automatically; selection only decides what is STORED,
# which is enforced in the filter transform below.

set -euo pipefail
. /opt/ai-terminal-logs/lib/common.sh
load_env

# Validate one config file, writing the reason to the state directory on failure.
#
# Vector moved `validate` from taking `--config <file>` to taking the path as a
# positional argument, and the two forms are not interchangeable — the old one
# now dies with "unexpected argument '--config' found" before it reads a single
# line of config. Try the current form and fall back only when the CLI rejected
# the ARGUMENT, never when it rejected the config: retrying a genuine config
# error under the other form would report it as a version problem.
validate_config() {
  local f="$1" out
  out=$(vector validate --no-environment "$f" 2>&1) && return 0

  case "$out" in
    *"unexpected argument"*|*"Found argument"*|*"USAGE:"*|*"Usage:"*)
      out=$(vector validate --no-environment --config "$f" 2>&1) && return 0
      ;;
  esac

  printf '%s\n' "$out" > "$STATE/vector-config.error"
  return 1
}

generate() {
  local tmp="$VECTOR_CONF.tmp"
  install -d -m 755 /etc/vector "$STATE/vector"

  local src_pm2 src_docker src_systemd src_nginx
  src_pm2=$(json_get     "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("pm2",True))'     2>/dev/null || echo True)
  src_docker=$(json_get  "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("docker",True))'  2>/dev/null || echo True)
  src_systemd=$(json_get "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("systemd",True))' 2>/dev/null || echo True)
  src_nginx=$(json_get   "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("nginx","off"))'  2>/dev/null || echo off)

  local services_json
  services_json=$(json_get "$CONF" logServices '[]')

  {
    cat <<EOF
# GENERATED by ai-terminal-logs — regenerated on every \`logagent set\`.
# Manual edits are lost. Change configuration via the CLI or the app.
data_dir = "$STATE/vector"

[api]
enabled = false
EOF

    # ── PM2 ──────────────────────────────────────────────────────────────────
    if [ "$src_pm2" = "True" ] && [ -n "${PM2_LOG_DIRS_CSV:-}" ]; then
      cat <<EOF

[sources.pm2]
type = "file"
include = [ $PM2_LOG_DIRS_CSV ]
read_from = "end"
ignore_older_secs = 86400      # never replay a year-old backlog on first start
# No include_file_metadata here. It is not an option of the file source, so
# validation rejected the whole config and the collector was never started.
# The path the parser needs arrives as .file anyway; file_key defaults to it.
# Note: no backticks in this heredoc — it is unquoted, so backticks would be
# run as command substitution while the config is being generated.

# A record begins at column 0; indented lines continue it. This is what makes a
# 30-line stack trace one row instead of thirty — error grouping depends on it.
[sources.pm2.multiline]
start_pattern     = '^\\S'
condition_pattern = '^\\s'
mode              = "continue_through"
timeout_ms        = 1000

# Identify files by inode, not by a checksum of their first line.
#
# Vector's default fingerprint is a checksum over lines = 1. Sibling PM2 logs
# routinely share a first line — the same framework banner in prod, stage and
# qa, or nothing at all in a file that has not been written to yet — so they
# collide. Vector then decides they are one file that keeps being renamed,
# watches only the most recently modified of the group, and attributes its lines
# to whichever name it settled on. That silently drops most services and files
# the rest under the wrong one, which is worse than collecting nothing: the
# dashboard looks healthy and is lying.
#
# The trade-off is inode reuse after deletion, which is rare and self-corrects
# at the next rotation. Collisions here are not rare; they are happening on
# every machine with more than one environment deployed.
[sources.pm2.fingerprint]
strategy = "device_and_inode"
EOF
    fi

    # ── Docker ───────────────────────────────────────────────────────────────
    # Reads the socket directly: discovers every container by name, picks up new
    # ones automatically, and needs no log-driver change — so production database
    # containers are never restarted.
    if [ "$src_docker" = "True" ]; then
      cat <<EOF

[sources.docker]
type = "docker_logs"
exclude_containers = ["$PG_CONTAINER"]
EOF
    fi

    if [ "$src_systemd" = "True" ] && [ "${HAS_JOURNAL:-0}" = "1" ]; then
      cat <<'EOF'

[sources.systemd]
type = "journald"
current_boot_only = false
EOF
    fi

    if [ "$src_nginx" != "off" ] && [ -n "${NGINX_LOG_DIR:-}" ]; then
      cat <<EOF

[sources.nginx]
type = "file"
include = [ "$NGINX_LOG_DIR/*.log" ]
read_from = "end"
ignore_older_secs = 86400

# Same reason as the PM2 source: access.log and error.log for several vhosts
# share opening lines and would be fingerprinted as one file.
[sources.nginx.fingerprint]
strategy = "device_and_inode"
EOF
    fi

    local inputs="[]"
    inputs=$(python3 - "$src_pm2" "$src_docker" "$src_systemd" "$src_nginx" "${HAS_JOURNAL:-0}" <<'PY'
import sys
pm2, docker, systemd, nginx, hasj = sys.argv[1:6]
out = []
if pm2 == "True": out.append("pm2")
if docker == "True": out.append("docker")
if systemd == "True" and hasj == "1": out.append("systemd")
if nginx != "off": out.append("nginx")
print("[" + ", ".join(f'"{s}"' for s in out) + "]")
PY
)

    cat <<EOF

[transforms.parse]
type = "remap"
inputs = $inputs
EOF

    cat <<'PARSE'
source = '''
  raw = to_string(.message) ?? ""

  # ── strip terminal escapes ───────────────────────────────────────────────
  # At ingest, not at render. Colour carries no information the database needs
  # — severity is already its own column — and leaving the escapes in breaks
  # everything downstream: a search for "Request completed" never matches
  # because the stored text is "\e[36mRequest completed\e[39m", error
  # fingerprints group on colour as well as message, and every consumer (app,
  # alert email, Telegram) would need its own decoder.
  #
  # PM2 and Docker capture a process's stdout verbatim, so on a colourised Node
  # service the escapes can outweigh the message itself.
  raw = replace(raw, r'\x1b\][^\x07\x1b]*(\x07|\x1b\\)', "")   # OSC (window title)
  raw = replace(raw, r'\x1b\[[0-9;?]*[ -/]*[@-~]', "")         # CSI (colour, cursor)
  raw = replace(raw, r'\x1b[@-Z\\-_]', "")                     # remaining two-byte escapes

  # ── service and kind ─────────────────────────────────────────────────────
  if exists(.container_name) {
    .service = string!(.container_name)
    .kind = "docker"
  } else if exists(._SYSTEMD_UNIT) {
    .service = string!(._SYSTEMD_UNIT)
    .kind = "systemd"
  } else if exists(.file) {
    path = string!(.file)
    # Basename by regex, not split()+index. VRL has no negative array indexing,
    # so `parts[-1]` fails to compile and `vector validate` rejects the entire
    # config — which leaves the collector stopped rather than degraded.
    tail = parse_regex(path, r'(?P<b>[^/]+)$') ?? null
    base = if tail != null { string!(tail.b) } else { path }
    # No string!() on base: both branches above yield a string, so the assertion
    # can never fire and VRL warns E620 "can't abort infallible function" on
    # every config load.
    if starts_with(path, "/var/log/nginx") {
      .service = replace(base, ".log", "")
      .kind = "nginx"
    } else {
      .service = replace(base, r'-(out|error)(-\d+)?\.log$', "")
      .kind = "pm2"
      .stream = if match(path, r'-error') { "stderr" } else { "stdout" }
    }
  } else {
    .service = "unknown"
    .kind = "unknown"
  }

  # ── timestamp ────────────────────────────────────────────────────────────
  # Three shapes seen in practice: bracketed with a UTC offset, bracketed
  # without one, and the bare form Postgres emits. Unparseable lines fall back
  # to ingest time rather than being discarded.
  ts = null
  bracket = parse_regex(raw, r'^\[(?P<t>[^\]]+)\]') ?? null
  if bracket != null {
    ts = parse_timestamp(bracket.t, "%Y-%m-%d %H:%M:%S%.3f %z") ??
         parse_timestamp(bracket.t, "%Y-%m-%d %H:%M:%S%.3f") ??
         parse_timestamp(bracket.t, "%Y-%m-%dT%H:%M:%S%.3f%z") ?? null
  }
  if ts == null {
    plain = parse_regex(raw, r'^(?P<t>\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}\.\d+)') ?? null
    if plain != null {
      ts = parse_timestamp(plain.t, "%Y-%m-%d %H:%M:%S%.3f") ??
           parse_timestamp(plain.t, "%Y-%m-%dT%H:%M:%S%.3f") ?? null
    }
  }
  # Vector already stamps every event, so an unparseable line falls back to
  # ingest time rather than being dropped.
  #
  # Two VRL rules make this more verbose than it looks. There is no
  # to_timestamp() — .timestamp is already a timestamp, so it is tested and
  # assigned rather than converted. And `??` coalesces ERRORS, not nulls: using
  # it on a plain variable is rejected outright with "this expression can't
  # fail", so a null has to be handled by an explicit branch.
  if ts == null && is_timestamp(.timestamp) { ts = .timestamp }
  if ts == null { ts = now() }
  .ts = format_timestamp!(ts, "%+")

  # ── severity ─────────────────────────────────────────────────────────────
  # NOT mapping pm2 stderr to ERROR. In practice PM2 error logs are full of
  # warnings; that mapping manufactures thousands of false errors and makes
  # alerting worthless from day one.
  up = upcase(raw)
  sev = null
  if      contains(up, "FATAL") || contains(up, "CRITICAL") { sev = "FATAL" }
  else if contains(up, "ERROR")                             { sev = "ERROR" }
  else if contains(up, "WARNING") || contains(up, "WARN")   { sev = "WARN" }
  else if contains(up, "DEBUG") || contains(up, "TRACE")    { sev = "DEBUG" }
  else if contains(up, "INFO") || contains(up, "NOTICE")    { sev = "INFO" }

  if sev == null {
    if contains(raw, "⚠") { sev = "WARN" }
    if contains(raw, "❌") || contains(raw, "🔴") { sev = "ERROR" }
  }

  # Declared out here, not inside the branch below. VRL scopes a variable to the
  # block it is assigned in, so a value produced inside `if sev == null` does not
  # exist afterwards — reading it later is error[E701]: undefined variable, and
  # the whole config is rejected.
  http = parse_regex(raw, r'\((?P<ms>\d+) ms\)\s+(?P<code>\d{3})\s*$') ?? null

  # HTTP access lines carry no level. Derive one from the status code so they
  # are filterable instead of an undifferentiated wall of INFO.
  if sev == null {
    if http != null {
      code = to_int(http.code) ?? 0
      sev = if code >= 500 { "ERROR" } else if code >= 400 { "WARN" } else { "INFO" }
    }
  }
  # Explicit branch, not `sev ?? "INFO"` — see the note above: `??` handles
  # errors, and a plain variable cannot error, so VRL rejects that form.
  if sev == null { sev = "INFO" }
  .severity = sev

  # ── request timing ───────────────────────────────────────────────────────
  # Every percentile in the app comes from this one field. It is extracted
  # OUTSIDE the severity branch above, which is where it used to live: a line
  # that already said "INFO" never reached the extractor, so any framework that
  # logs a level and a duration on the same line — which is most of them,
  # certainly Pino and Bunyan — produced no latency data at all while looking
  # perfectly healthy.
  #
  # Three shapes, most specific first. Deliberately not "any number followed by
  # ms anywhere in the line": a retry backoff or a cache TTL would be recorded
  # as request latency, and a p95 built from those is worse than a blank chart
  # because it looks like an answer.
  ms = null

  # Pino, Bunyan, structured logs, key=value: responseTime: 42, duration_ms=12,
  # "elapsed":"1.5s", took=900ms.
  kv = parse_regex(raw, r'(?i)\b(?:response_?time(?:_?ms)?|duration_?(?:ms)?|elapsed(?:_?ms)?|latency(?:_?ms)?|took|rt)\b"?\s*[=:]\s*"?(?P<n>\d+(?:\.\d+)?)\s*(?P<unit>ms|s\b)?') ?? null
  if kv != null {
    n = to_float(kv.n) ?? 0.0
    # A bare number under one of these keys is milliseconds by convention.
    if kv.unit == "s" { n = n * 1000.0 }
    ms = n
  }

  # The shape the previous parser handled: `... (123 ms) 200`.
  if ms == null {
    paren = parse_regex(raw, r'\((?P<n>\d+(?:\.\d+)?) ?ms\)') ?? null
    if paren != null { ms = to_float(paren.n) ?? 0.0 }
  }

  # Morgan's default format ends `- 12.345 ms`, and nginx logs configured with
  # $request_time follow the same tail.
  if ms == null {
    morgan = parse_regex(raw, r'-\s+(?P<n>\d+(?:\.\d+)?)\s*ms\s*$') ?? null
    if morgan != null { ms = to_float(morgan.n) ?? 0.0 }
  }

  status = null
  st = parse_regex(raw, r'(?i)\b(?:status(?:_?code)?|statuscode)\b"?\s*[=:]\s*"?(?P<c>\d{3})\b') ?? null
  if st != null { status = to_int(st.c) ?? null }
  if status == null && http != null { status = to_int(http.code) ?? null }

  # Built as one object rather than assigned twice: a second `.attrs = {...}`
  # replaces the first, so writing status and duration separately would silently
  # drop whichever came first.
  if ms != null || status != null {
    attrs = {}
    if ms != null     { attrs = set!(attrs, ["duration_ms"], ms) }
    if status != null { attrs = set!(attrs, ["status"], status) }
    .attrs = attrs
  }

  # ── redaction ────────────────────────────────────────────────────────────
  # Applied BEFORE the write. This store is queried from a phone and kept for
  # days; a credential must never reach the database in the first place.
  raw = replace(raw, r'(?i)(password|passwd|pwd|secret|api[_-]?key|apikey|token|authorization)\s*[=:]\s*\S+', "$1=***")
  raw = replace(raw, r'(?i)bearer\s+[A-Za-z0-9\-\._~\+/]+=*', "Bearer ***")
  raw = replace(raw, r'eyJ[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]*', "***")
  raw = replace(raw, r'AKIA[0-9A-Z]{16}', "***")
  raw = replace(raw, r'://([^:/@\s]+):([^@/\s]+)@', "://$1:***@")

  .body = raw
  .host = "HOST_PLACEHOLDER"

  del(.message); del(.file); del(.source_type); del(.stream); del(.timestamp)
  del(.container_id); del(.container_created_at); del(.image); del(.label)
  del(.host_name); del(._SYSTEMD_UNIT); del(.PRIORITY)
'''
PARSE

    # Selection filter. An empty allowlist stores nothing — the agent installs
    # paused and must not begin consuming disk before the user chooses.
    cat <<EOF

[transforms.selected]
type = "filter"
inputs = ["parse"]
# No error-coalescing operator here: includes() cannot fail, and VRL rejects
# coalescing on an expression that cannot error. An empty allowlist already
# yields false, which is the behaviour that matters — the agent must store
# nothing until services are chosen.
# (This heredoc is unquoted: no backticks, they would be run as commands.)
condition = '''
  includes($services_json, .service)
'''

[sinks.receiver]
type = "http"
inputs = ["selected"]
uri = "http://127.0.0.1:${RECEIVER_PORT:-9080}/"
method = "post"
encoding.codec = "json"
framing.method = "newline_delimited"

[sinks.receiver.batch]
max_events = 500
timeout_secs = 5

# Disk buffer, capped. Survives a receiver restart without losing data, and
# drops rather than growing without bound — the agent must never OOM the host.
[sinks.receiver.buffer]
type = "disk"
max_size = 268435488
when_full = "drop_newest"

[sinks.receiver.request]
retry_attempts = 10
timeout_secs = 30
EOF
  } > "$tmp"

  sed -i "s/HOST_PLACEHOLDER/${HOST_NAME:-$(hostname)}/" "$tmp"

  # Fail loudly. Installing a config that silently collects nothing is the worst
  # outcome, so validation is mandatory and the old config is kept on failure.
  #
  # The error is also persisted, not just printed. A rejected config leaves the
  # collector stopped with no fault of its own — systemd reports a perfectly
  # healthy "inactive (dead)" unit — so without this the only trace of the real
  # reason is a line of installer output that has already scrolled away.
  if ! validate_config "$tmp"; then
    warn "generated vector config failed validation:"
    sed 's/^/    /' "$STATE/vector-config.error" >&2
    rm -f "$tmp"
    return 1
  fi
  rm -f "$STATE/vector-config.error"

  mv "$tmp" "$VECTOR_CONF"
  log "vector config written and validated"
}

reload_vector() {
  local paused
  paused=$(json_get "$CONF" paused true)
  if [ "$paused" = "true" ]; then
    systemctl stop vector >/dev/null 2>&1 || true
    log "agent is paused — vector stopped"
    return 0
  fi

  systemctl restart vector >/dev/null 2>&1 || true

  # Verify, do not assume. `systemctl restart` on a missing or broken unit fails
  # in a way that used to be swallowed, leaving an agent that reports itself
  # configured and unpaused while collecting nothing — the one failure mode this
  # project exists to prevent. Say so, and say where to look.
  if systemctl is-active --quiet vector; then
    log "vector running"
  else
    warn "vector is NOT running — no logs will be collected"
    systemctl status vector --no-pager --lines=10 >&2 2>&1 || true
    journalctl -u vector --no-pager --lines=20 >&2 2>&1 || true
    return 1
  fi
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  # PM2 dirs are re-detected here so the CLI can regenerate without the installer.
  dirs=""
  for d in /root/.pm2/logs /home/*/.pm2/logs; do
    [ -d "$d" ] && dirs="$dirs\"$d/*.log\", "
  done
  export PM2_LOG_DIRS_CSV="${dirs%, }"
  [ -d /var/log/nginx ] && export NGINX_LOG_DIR=/var/log/nginx
  command -v journalctl >/dev/null 2>&1 && export HAS_JOURNAL=1
  generate && reload_vector
fi
