#!/usr/bin/env bash
# Generate /etc/vector/vector.toml from the current selection in logagent.conf.
#
# Standalone and idempotent, so `logagent set` can rebuild the config and restart
# Vector without reinstalling anything.
#
# Sources are declared per source TYPE, never per service. A new PM2 app or
# container is picked up automatically; selection only decides what is STORED,
# which is enforced in the filter transform below.

set -euo pipefail
. /opt/ai-terminal-logs/lib/common.sh
load_env

generate() {
  local tmp="$VECTOR_CONF.tmp"
  install -d -m 755 /etc/vector "$STATE/vector"

  local src_pm2 src_docker src_systemd src_nginx
  src_pm2=$(json_get     "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("pm2",True))'     2>/dev/null || echo True)
  src_docker=$(json_get  "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("docker",True))'  2>/dev/null || echo True)
  src_systemd=$(json_get "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("systemd",True))' 2>/dev/null || echo True)
  src_nginx=$(json_get   "$CONF" sources '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin).get("nginx","off"))'  2>/dev/null || echo off)

  local services_json
  services_json=$(json_get "$CONF" logServices '[]')

  {
    cat <<EOF
# GENERATED by ai-terminal-logs — regenerated on every \`logagent set\`.
# Manual edits are lost. Change configuration via the CLI or the app.
data_dir = "$STATE/vector"

[api]
enabled = false
EOF

    # ── PM2 ──────────────────────────────────────────────────────────────────
    if [ "$src_pm2" = "True" ] && [ -n "${PM2_LOG_DIRS_CSV:-}" ]; then
      cat <<EOF

[sources.pm2]
type = "file"
include = [ $PM2_LOG_DIRS_CSV ]
read_from = "end"
ignore_older_secs = 86400      # never replay a year-old backlog on first start
include_file_metadata = true

# A record begins at column 0; indented lines continue it. This is what makes a
# 30-line stack trace one row instead of thirty — error grouping depends on it.
[sources.pm2.multiline]
start_pattern     = '^\\S'
condition_pattern = '^\\s'
mode              = "continue_through"
timeout_ms        = 1000
EOF
    fi

    # ── Docker ───────────────────────────────────────────────────────────────
    # Reads the socket directly: discovers every container by name, picks up new
    # ones automatically, and needs no log-driver change — so production database
    # containers are never restarted.
    if [ "$src_docker" = "True" ]; then
      cat <<EOF

[sources.docker]
type = "docker_logs"
exclude_containers = ["$PG_CONTAINER"]
EOF
    fi

    if [ "$src_systemd" = "True" ] && [ "${HAS_JOURNAL:-0}" = "1" ]; then
      cat <<'EOF'

[sources.systemd]
type = "journald"
current_boot_only = false
EOF
    fi

    if [ "$src_nginx" != "off" ] && [ -n "${NGINX_LOG_DIR:-}" ]; then
      cat <<EOF

[sources.nginx]
type = "file"
include = [ "$NGINX_LOG_DIR/*.log" ]
read_from = "end"
ignore_older_secs = 86400
include_file_metadata = true
EOF
    fi

    local inputs="[]"
    inputs=$(python3 - "$src_pm2" "$src_docker" "$src_systemd" "$src_nginx" "${HAS_JOURNAL:-0}" <<'PY'
import sys
pm2, docker, systemd, nginx, hasj = sys.argv[1:6]
out = []
if pm2 == "True": out.append("pm2")
if docker == "True": out.append("docker")
if systemd == "True" and hasj == "1": out.append("systemd")
if nginx != "off": out.append("nginx")
print("[" + ", ".join(f'"{s}"' for s in out) + "]")
PY
)

    cat <<EOF

[transforms.parse]
type = "remap"
inputs = $inputs
EOF

    cat <<'PARSE'
source = '''
  raw = to_string(.message) ?? ""

  # ── service and kind ─────────────────────────────────────────────────────
  if exists(.container_name) {
    .service = string!(.container_name)
    .kind = "docker"
  } else if exists(._SYSTEMD_UNIT) {
    .service = string!(._SYSTEMD_UNIT)
    .kind = "systemd"
  } else if exists(.file) {
    path = string!(.file)
    name = split(path, "/") ?? []
    base = if length(name) > 0 { name[-1] } else { path }
    if starts_with(path, "/var/log/nginx") {
      .service = replace(string!(base), ".log", "")
      .kind = "nginx"
    } else {
      .service = replace(string!(base), r'-(out|error)(-\d+)?\.log$', "")
      .kind = "pm2"
      .stream = if match(path, r'-error') { "stderr" } else { "stdout" }
    }
  } else {
    .service = "unknown"
    .kind = "unknown"
  }

  # ── timestamp ────────────────────────────────────────────────────────────
  # Three shapes seen in practice: bracketed with a UTC offset, bracketed
  # without one, and the bare form Postgres emits. Unparseable lines fall back
  # to ingest time rather than being discarded.
  ts = null
  bracket = parse_regex(raw, r'^\[(?P<t>[^\]]+)\]') ?? null
  if bracket != null {
    ts = parse_timestamp(bracket.t, "%Y-%m-%d %H:%M:%S%.3f %z") ??
         parse_timestamp(bracket.t, "%Y-%m-%d %H:%M:%S%.3f") ??
         parse_timestamp(bracket.t, "%Y-%m-%dT%H:%M:%S%.3f%z") ?? null
  }
  if ts == null {
    plain = parse_regex(raw, r'^(?P<t>\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}\.\d+)') ?? null
    if plain != null {
      ts = parse_timestamp(plain.t, "%Y-%m-%d %H:%M:%S%.3f") ??
           parse_timestamp(plain.t, "%Y-%m-%dT%H:%M:%S%.3f") ?? null
    }
  }
  if ts == null && exists(.timestamp) { ts = to_timestamp(.timestamp) ?? null }
  .ts = format_timestamp!(ts ?? now(), "%+")

  # ── severity ─────────────────────────────────────────────────────────────
  # NOT mapping pm2 stderr to ERROR. In practice PM2 error logs are full of
  # warnings; that mapping manufactures thousands of false errors and makes
  # alerting worthless from day one.
  up = upcase(raw)
  sev = null
  if      contains(up, "FATAL") || contains(up, "CRITICAL") { sev = "FATAL" }
  else if contains(up, "ERROR")                             { sev = "ERROR" }
  else if contains(up, "WARNING") || contains(up, "WARN")   { sev = "WARN" }
  else if contains(up, "DEBUG") || contains(up, "TRACE")    { sev = "DEBUG" }
  else if contains(up, "INFO") || contains(up, "NOTICE")    { sev = "INFO" }

  if sev == null {
    if contains(raw, "⚠") { sev = "WARN" }
    if contains(raw, "❌") || contains(raw, "🔴") { sev = "ERROR" }
  }

  # HTTP access lines carry no level. Derive one from the status code so they
  # are filterable instead of an undifferentiated wall of INFO.
  if sev == null {
    http = parse_regex(raw, r'\((?P<ms>\d+) ms\)\s+(?P<code>\d{3})\s*$') ?? null
    if http != null {
      code = to_int(http.code) ?? 0
      sev = if code >= 500 { "ERROR" } else if code >= 400 { "WARN" } else { "INFO" }
      .attrs = { "status": code, "duration_ms": to_int(http.ms) ?? 0 }
    }
  }
  .severity = sev ?? "INFO"

  # ── redaction ────────────────────────────────────────────────────────────
  # Applied BEFORE the write. This store is queried from a phone and kept for
  # days; a credential must never reach the database in the first place.
  raw = replace(raw, r'(?i)(password|passwd|pwd|secret|api[_-]?key|apikey|token|authorization)\s*[=:]\s*\S+', "$1=***")
  raw = replace(raw, r'(?i)bearer\s+[A-Za-z0-9\-\._~\+/]+=*', "Bearer ***")
  raw = replace(raw, r'eyJ[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]*', "***")
  raw = replace(raw, r'AKIA[0-9A-Z]{16}', "***")
  raw = replace(raw, r'://([^:/@\s]+):([^@/\s]+)@', "://$1:***@")

  .body = raw
  .host = "HOST_PLACEHOLDER"

  del(.message); del(.file); del(.source_type); del(.stream); del(.timestamp)
  del(.container_id); del(.container_created_at); del(.image); del(.label)
  del(.host_name); del(._SYSTEMD_UNIT); del(.PRIORITY)
'''
PARSE

    # Selection filter. An empty allowlist stores nothing — the agent installs
    # paused and must not begin consuming disk before the user chooses.
    cat <<EOF

[transforms.selected]
type = "filter"
inputs = ["parse"]
condition = '''
  includes($services_json, .service) ?? false
'''

[sinks.receiver]
type = "http"
inputs = ["selected"]
uri = "http://127.0.0.1:${RECEIVER_PORT:-9080}/"
method = "post"
encoding.codec = "json"
framing.method = "newline_delimited"

[sinks.receiver.batch]
max_events = 500
timeout_secs = 5

# Disk buffer, capped. Survives a receiver restart without losing data, and
# drops rather than growing without bound — the agent must never OOM the host.
[sinks.receiver.buffer]
type = "disk"
max_size = 268435488
when_full = "drop_newest"

[sinks.receiver.request]
retry_attempts = 10
timeout_secs = 30
EOF
  } > "$tmp"

  sed -i "s/HOST_PLACEHOLDER/${HOST_NAME:-$(hostname)}/" "$tmp"

  # Fail loudly. Installing a config that silently collects nothing is the worst
  # outcome, so validation is mandatory and the old config is kept on failure.
  if ! vector validate --no-environment --config "$tmp" >/tmp/vector-validate.log 2>&1; then
    warn "generated vector config failed validation:"
    sed 's/^/    /' /tmp/vector-validate.log >&2
    rm -f "$tmp"
    return 1
  fi

  mv "$tmp" "$VECTOR_CONF"
  log "vector config written and validated"
}

reload_vector() {
  local paused
  paused=$(json_get "$CONF" paused true)
  if [ "$paused" = "true" ]; then
    systemctl stop vector >/dev/null 2>&1 || true
    log "agent is paused — vector stopped"
    return 0
  fi

  systemctl restart vector >/dev/null 2>&1 || true

  # Verify, do not assume. `systemctl restart` on a missing or broken unit fails
  # in a way that used to be swallowed, leaving an agent that reports itself
  # configured and unpaused while collecting nothing — the one failure mode this
  # project exists to prevent. Say so, and say where to look.
  if systemctl is-active --quiet vector; then
    log "vector running"
  else
    warn "vector is NOT running — no logs will be collected"
    systemctl status vector --no-pager --lines=10 >&2 2>&1 || true
    journalctl -u vector --no-pager --lines=20 >&2 2>&1 || true
    return 1
  fi
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  # PM2 dirs are re-detected here so the CLI can regenerate without the installer.
  dirs=""
  for d in /root/.pm2/logs /home/*/.pm2/logs; do
    [ -d "$d" ] && dirs="$dirs\"$d/*.log\", "
  done
  export PM2_LOG_DIRS_CSV="${dirs%, }"
  [ -d /var/log/nginx ] && export NGINX_LOG_DIR=/var/log/nginx
  command -v journalctl >/dev/null 2>&1 && export HAS_JOURNAL=1
  generate && reload_vector
fi
